### ISSUE TITLE
Compilation error on file lib/hedwig_xmpp.ex 

### ISSUE THREAD

**Issue by bossyang** [hedwig-im/hedwig_xmpp#2]
OS X 10.11.6
elixir 1.3.2
Erlang/OTP R19

Also failed with elixir 1.2.5/OTP R18.

```
===> Compiling p1_utils
===> Compiling fast_xml
==> hedwig_xmpp
Compiling 1 file (.ex)

== Compilation error on file lib/hedwig_xmpp.ex ==
** (CompileError) lib/hedwig_xmpp.ex:4: module Hedwig.Adapter is not loaded and could not be found
    (elixir) expanding macro: Kernel.use/1
    lib/hedwig_xmpp.ex:4: Hedwig.Adapters.XMPP (module)
    (elixir) lib/kernel/parallel_compiler.ex:116: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1

could not compile dependency :hedwig_xmpp, "mix compile" failed. You can recompile this dependency with "mix deps.compile hedwig_xmpp", update it with "mix deps.update hedwig_xmpp" or clean it with "mix deps.clean hedwig_xmpp"
```

**Comment by RuthraiahThulasi** [comment]
Add the following line in your dep 

[ {:hedwig_xmpp, github: "hedwig-im/hedwig_xmpp"}]

**Comment by bossyang** [comment]
@RuthraiahThulasi Thanks!
